---
title: "Week 3"
author: "Richy Varghese"
date: "February 16, 2019"
output: html_document
---

###Checking workspace and objects in it
```{r}
#Getting the working directory
getwd()
#Getting the list of objects in the directory using ls()
ls()
```

###Creating and saving objects
```{r}
sample.df <- data.frame(id = 1:5, grades = c("a", "b", "c", "d", "f"), counts = c(10, 20, 30, 15, 5))
counts.by.grades <- aggregate(counts ~ grades, FUN = mean, data = sample.df)
#Saving into a new .RData file
save(sample.df, counts.by.grades, file = "C:/Users/Richy/Desktop/Harrisburg University/Exploratory Data Analytics/FinalProject/ANLY506_RichyVarghese_FinalProject/Portfolio/Week 3/Sample.RData")
```

###Loading objects
```{r}
#Loading objects from the above created .RData file
load(file = "C:/Users/Richy/Desktop/Harrisburg University/Exploratory Data Analytics/FinalProject/ANLY506_RichyVarghese_FinalProject/Portfolio/Week 3/Sample.RData")
```

###Removing objects
```{r}
#Removing objects using rm()
rm(sample.df)
```