---
title: "Week 6"
author: "Richy Varghese"
date: "February 16, 2019"
output: html_document
---

###Creating a matrix
```{r}
a <- 11:15
b <- 16:20
c <- 21:25
#Creating a matrix with a, b, c as columns
cbind(a, b, c)
#Creating a matrix with a, b, c as rows
rbind(a, b, c)
#Using matrix() to create a matrix
matrix(data = 1:20,
       nrow = 5,
       ncol = 4)
```

###Creating a dataframe
```{r}
#Creating a dataframe using data.frame()
test <- data.frame("index" = c(1, 2, 3, 4, 5),"grade" = c("a", "b", "c", "d", "f"), "students" = c(10, 20, 30, 15, 5))
test
#Checking structure of dataframe
str(test)
#Creating dataframe without factors
test <- data.frame("index" = c(1, 2, 3, 4, 5),"grade" = c("a", "b", "c", "d", "f"), "students" = c(10, 20, 30, 15, 5), stringsAsFactors = FALSE)
str(test)
#Checking column names of dataframe
names(test)
#Adding new column to dataframe
test$mean <- c(92, 85, 75, 69, 30)
test
#Changing name of column
names(test)[1] <- "index number"
test
```

###Slicing dataframes
```{r}
test
#Returning row 1
test[1,]
#Returning column 2
test[,2]
#Returning rows 1:3 and column 2
test[1:3,2]
#Slicing using subset()
subset(x = test, subset = grade == "a" | grade == "b")
#Using with() to get percentage of students
with(test, students/sum(students))
```